name: Test and Lint flake

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    if: github.repository == 'auxera/nix-templates'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Verify flake configuration
        run: nix develop -c nix flake check . --all-systems

      - name: Lint Nix code with Alejandra
        run: nix develop -c alejandra --check .

      - name: Approve pull request
        if: github.event_name == 'pull_request'
        uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
          review-message: 'Auto-approved as all checks passed.'